version: 0.2
phase:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "installing packages..."
      - echo "Packages installed successfully."
  pre_build:
    commands:
      - echo "Testing..."
      - echo "Tests passed successfully."

  build:
    commands:
      - echo "Starting compiling packages....."
      - echo "Build passed successfully."
  post_build:
    commands:
      - echo "Performing post-build packing and operations..."
      - echo "Post build successful"
artifacts:
  files:
    - '**/*'
  name: meetfoodclasscode
